networks:
  backend:
    external: true

volumes:
  nodered_data:
  grafana_data:
  influx_data:
  # influx_config:
  mosquittoLog:
  mosquitto_data:

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    volumes:
      - nodered_data:/data  # Use o nome do volume definido acima
    environment:
      - TZ=Europe/Berlin
      - NODE_RED_USERNAME=${NODE_RED_USERNAME}
      - NODE_RED_PASSWORD=${NODE_RED_PASSWORD}
    networks:
      - backend
    ports:
      - "1880:1880"

  grafana:      
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes: 
      - grafana_data:/var/lib/grafana
    networks:
    - backend

  influxdb:
    image: influxdb
    container_name: influxdb
    restart: unless-stopped
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
    ports:
      - "8082:8082"
      - "8086:8086" #UI
      - "8089:8089"
    volumes:
      - influx_data:/var/lib/influxdb
    networks: 
      - backend 
    
  mosquitto:
    image: eclipse-mosquitto:latest
    restart: always
    container_name: mosquitto
    stdin_open: true
    tty: true
    #deploy:
    #  resources:
    #    limits:
     #     memory: 256M
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquittoLog:/mosquitto/log
    #security_opt:
      #- no-new-privileges:true 
    ports:
      - 1883:1883 # 1883 is in use?
      - 9001:9001
    networks:
       - backend