networks:
  backend:
    external: true

volumes:
  uptimekuma_data:

services:
  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    volumes:
      - uptimekuma_data:/app/data
    restart: unless-stopped
    networks:
      - backend
