services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"  # Console/API
      - "9001:9001"  # UI
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - datanet


volumes:
  minio_data:
  
networks:
  datanet:
