services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
       - 1883:1883 
    volumes:
      - /home/rato/docker/mosquitto/config:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    stdin_open: true
    tty: true

volumes:
  mosquitto_data:
  mosquitto_log:
