services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: ${SQL_SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - /var/opt/mssql/dwh_project:/mnt/dwh_project:ro # Mounting the DWH project directory as read-only
    restart: always

volumes:
  sql_data: