services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=db_w
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
    volumes:
      - wordpress:/var/www/html
    networks:
      - backend

  db_w:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_w:/var/lib/mysql
    networks:
      - backend

volumes:
  wordpress:
  db_w:

networks:
  backend:
    external: true 
