FROM apache/airflow:latest

USER root
RUN apt-get update && \
    apt-get -y install git curl unzip nano && \
    apt-get clean

COPY requirements.txt .

USER airflow
RUN pip install --no-cache-dir -r requirements.txt

USER root
RUN chown -R airflow: /opt/airflow

USER airflow
